platform :ios, "8.0"
use_frameworks!

target 'Example' do
    pod 'TransitionTreasury', '~>3.0.3'
    pod 'TransitionAnimation', '~>3.0.3'
end

target 'ExampleWithoutAnimation' do
    pod 'TransitionTreasury', '~>3.0.3'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
