source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

# Our Libraries
def libraries
  pod 'TransitionTreasury', :path => "../"
  pod 'TransitionAnimation', :path => "../"
end

target 'Demo' do
    libraries
end

target 'TabBarDemo' do
  libraries
end

